services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0902
      - POSTGRES_DB=datascrub
    ports:
      - 5432:5432
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=markb@aimagineers.io
      - PGADMIN_DEFAULT_PASSWORD=0902
    ports:
      - 5050:80
    restart: always
  
  redis:
    image: redis:7.0.15-alpine

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
     - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=MetalGear0302
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=data_scrub worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=MetalGear0302
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1

volumes:
  postgres_data: