# Generated by Django 5.0.6 on 2024-05-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitue', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('dew_point', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('precipitation_prob', models.FloatField()),
                ('snow', models.FloatField(blank=True, null=True)),
                ('snow_depth', models.FloatField(blank=True, null=True)),
                ('wind_gust', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('pressure', models.FloatField()),
                ('visibility', models.FloatField()),
                ('cloud_cover', models.IntegerField()),
                ('solar_radation', models.FloatField()),
                ('solar_energy', models.FloatField(blank=True, null=True)),
                ('uv_index', models.IntegerField()),
                ('severe_risk', models.IntegerField()),
                ('conditions', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrubbers.region')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrubbers.weatherdata')),
            ],
        ),
    ]
