# Generated by Django 5.0.6 on 2024-05-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.CharField(default='Philippines', max_length=255),
        ),
    ]
