# Generated by Django 5.0.6 on 2024-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubbers', '0002_region_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='regional_center',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
