# Generated by Django 5.0.6 on 2024-05-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrubbers', '0003_region_regional_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='latitue',
            new_name='latitude',
        ),
    ]
