# Generated by Django 5.0.6 on 2024-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubbers', '0010_technologynews_technews_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busnews_metrics',
            name='named_entities',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busnews_metrics',
            name='sentiment_classification',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busnews_metrics',
            name='summary',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polnews_metrics',
            name='named_entities',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polnews_metrics',
            name='sentiment_classification',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polnews_metrics',
            name='summary',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technews_metrics',
            name='named_entities',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technews_metrics',
            name='sentiment_classification',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technews_metrics',
            name='summary',
            field=models.CharField(blank=True, null=True),
        ),
    ]
